# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gJQU97z82HAvd7lpY78yHDWGdUHN_BXM

### `app.py` - Streamlit Application Code
"""

pip install streamlit pandas joblib

import streamlit as st
import pandas as pd
import joblib

# Load the trained model
# Make sure 'random_forest_regressor_model.pkl' is in the same directory as this app.py file
try:
    model = joblib.load('random_forest_regressor_model.pkl')
    st.success('Model loaded successfully!')
except FileNotFoundError:
    st.error('Error: Model file `random_forest_regressor_model.pkl` not found. Please ensure it is in the same directory.')
    st.stop()
except Exception as e:
    st.error(f'Error loading model: {e}')
    st.stop()

# Set up the Streamlit app title and description
st.title('Random Forest Regressor Model Deployment')
st.write('Enter the feature values below to get a prediction.')

# --- Input Features (Customize these based on your model's training data) ---
st.header('Input Features')

# User-specified input features using Streamlit widgets
manufacturing_year = st.slider('Manufacturing Year', 1990, 2026, 2020, step=1)
kilometers_driven = st.slider('Kilometers Driven', 0, 500000, 50000)
fuel_type = st.radio('Fuel Type', ["Petrol","Diesel","CNG","LPG"])
seller_type = st.radio('Seller Type', ["Dealer","Individual"])
transmission = st.radio('Transmission', ["Manual","Automatic"])
owner_type = st.radio('Owner', ["First Owner","Second Owner","Third Owner","Fourth Owner","Fifth & Above Owner"])

# --- Feature Encoding (Adjust this to match your model's preprocessing) ---
# Example: Simple label encoding for categorical features

fuel_type_encoded = {
    "Petrol": 0,
    "Diesel": 1,
    "CNG": 2,
    "LPG": 3
}.get(fuel_type, -1) # -1 or raise error for unknown category

seller_type_encoded = {
    "Dealer": 0,
    "Individual": 1
}.get(seller_type, -1)

transmission_encoded = {
    "Manual": 0,
    "Automatic": 1
}.get(transmission, -1)

owner_type_encoded = {
    "First Owner": 0,
    "Second Owner": 1,
    "Third Owner": 2,
    "Fourth Owner": 3,
    "Fifth & Above Owner": 4
}.get(owner_type, -1)

# Create a DataFrame for the input features
# Ensure the column names match the features used during model training EXACTLY
input_data = pd.DataFrame([{
    'Manufacturing Year': manufacturing_year,
    'Kilometers Driven': kilometers_driven,
    'Fuel Type': fuel_type_encoded,
    'Seller Type': seller_type_encoded,
    'Transmission': transmission_encoded,
    'Owner': owner_type_encoded
}])

st.write('### Input Data Preview:')
st.dataframe(input_data)

# --- Prediction ---
if st.button('Get Prediction'):
    try:
        prediction = model.predict(input_data)
        st.success(f'The predicted value is: **{prediction[0]:.2f}**')
    except Exception as e:
        st.error(f'An error occurred during prediction: {e}')
        st.warning('Please ensure your input features match the model\'s expected format and types.')

"""### How to Run This Streamlit App:

1.  **Save the code:** Copy the content of the Python cell above (starting from `import streamlit as st` to the end) and save it as a file named `app.py` in a directory.
2.  **Place your model:** Make sure your `random_forest_regressor_model.pkl` file is in the *same directory* as `app.py`.
3.  **Install Streamlit and Joblib:** If you haven't already, install the necessary libraries:
    ```bash
    pip install streamlit pandas joblib
    ```
4.  **Run the app:** Open your terminal, navigate to the directory where you saved `app.py`, and run the following command:
    ```bash
    streamlit run app.py
    ```
    This will open the Streamlit application in your web browser.
"""